server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newlife?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: woshiniba1
  application:
    name: tv-video